version: '3.5'

services:
    test_app:
        image: damirchikr/bi.zone_test:latest
        container_name: test_app
        restart: always
        environment:
            - ENDPOINT_HOST
            - ENDPOINT_PORT=5001
        ports:
            - 5000:5001

