version: '3.5'

services:
    test_app:
        image: bizone_test:0.0.1
        container_name: test_app
        restart: always
        environment:
            - ENDPOINT_HOST
            - ENDPOINT_PORT=5001
        ports:
            - 5000:5001

